---
# tasks file for tom
- name: install tomcat
  yum: 
    name: tomcat
    state: present
- name: Tomcat configuration
  templates:
   src: templates/tomacatconfiguration.j2
   dest: /usr/share/tomcat/conf/tomcat.conf
  notify: tomstart
- name: Tomcat Installation
  yum:
    name: "{{ items }}"
    state: present
  with_items:
      - tomcat-webapps
      - tomcat-admin-webapps
- name: Tomcat User configuration
  templates:
   src: templates/tomcatuser.j2
   dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: tomrestart